import ProviderWrapper from "@/components/providers/ProviderWrapper";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-lg:text-sm`}>
        <AnimatePresence mode="wait">
          <ProviderWrapper>
            <Header />
            {children}
          </ProviderWrapper>
        </AnimatePresence>
      </body>
    </html>
  );
}
