import ProviderWrapper from "@/components/providers/ProviderWrapper";
import Header from "@/components/layout/Header";
import type { Metadata, Viewport } from "next";

import { GeistSans } from "geist/font/sans";

import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export const metadata: Metadata = {
	title: "Lance",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${GeistSans.className}`} id="mainbody">
				<ProviderWrapper>
					<Header />
					<SpeedInsights />
					{children}
				</ProviderWrapper>
			</body>
		</html>
	);
}
