import ProviderWrapper from "@/components/providers/ProviderWrapper";
import Header from "@/components/layout/Header";
import type { Metadata, Viewport } from "next";

import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { Menu } from "@/components/misc/Menu";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export const metadata: Metadata = {
	title: "Lance",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`} id="mainbody">
				<ProviderWrapper>
					<Header />
					<SpeedInsights />
					{children}
				</ProviderWrapper>
			</body>
		</html>
	);
}
